// Generated by dia2code
#ifndef SERVER__LOCALSERVER__H
#define SERVER__LOCALSERVER__H

#include <iostream>

namespace ia {
  class AI;
};
namespace server {
  class Server;
}

#include "Server.h"
#include "ia/AI.h"

namespace server {

  /// class LocalServer - 
  class LocalServer : public server::Server, public ia::AI {
    // Attributes
  protected:
    ia::AI* cmpt;
    // Operations
  public:
    LocalServer (ia::AI* cmpt);
    ~LocalServer ();
    void run ();
  };

};

#endif
