// Generated by dia2code
#ifndef SERVER__OBSERVABLE__H
#define SERVER__OBSERVABLE__H

#include <iostream>
#include <vector>

namespace server {
  class ServerObserver;
}

#include "ServerObserver.h"
#include "ServerEvent.h"

namespace server {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  protected:
    mutable std::vector<ServerObserver*> observers;
    // Operations
  public:
    void addObserver (ServerObserver* obs) const;
    void deleteObserver (ServerObserver* obs) const;
    virtual void notifyObserver (const ServerEvent& e) const = 0;
    virtual ~Observable ();
  };

};

#endif
