// Generated by dia2code
#ifndef SERVER__SERVEREVENT__H
#define SERVER__SERVEREVENT__H

#include <iostream>

namespace server {

  enum ServerEvent {
    INVALID     = 0,
    STATE_CHANGED     = 1
  };

};

#endif
