// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H

#include <iostream>

namespace engine {

  /// class Action - 
  class Action {
    // Operations
  public:
    virtual ~Action ();
    virtual void execute () const = 0;
  };

};

#endif
