// Generated by dia2code
#ifndef ENGINE__ACTIONLIST__H
#define ENGINE__ACTIONLIST__H

#include <iostream>
#include <vector>

namespace engine {
  class Action;
};
namespace state {
  class State;
}

#include "state/State.h"
#include "Action.h"

namespace engine {

  /// class ActionList - 
  class ActionList {
    // Associations
    // Attributes
  public:
    std::vector<Action*> actions;
    // Operations
  public:
    ActionList (std::vector<Action*> actions);
    ~ActionList ();
    int size () const;
    Action* get (int i) const;
    void add (Action* action);
    void addaply (Action* action);
  };

};

#endif
