// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H

#include <iostream>

namespace state {
  class Element;
  class ElementList;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"
#include "state/Element.h"
#include "state/ElementList.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Attributes
  protected:
    state::Element* attacker;
    state::Element* defender;
    state::ElementList* StaticMap;
    state::ElementList* MapUnits;
    // Operations
  public:
    AttackCommand (state::Element* attacker, state::Element* defender, state::ElementList* StaticMap, state::ElementList* MapUnits);
    ~AttackCommand ();
    CommandTypeID getCommandTypeID () const;
    state::Element* getAttacker ();
    state::Element* getDefender ();
    state::ElementList* getStaticMap ();
    state::ElementList* getMapUnits ();
  };

};

#endif
