// Generated by dia2code
#ifndef ENGINE__ATTACKENEMYUNIT__H
#define ENGINE__ATTACKENEMYUNIT__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class AttackEnemyUnit - 
  class AttackEnemyUnit : public engine::Action {
    // Attributes
  protected:
    int attacker;
    int defender;
    // Operations
  public:
    void AttackEnemyUnit (int attacker, int defender);
    void ~AttackEnemyUnit () const;
    void apply (state::State& s, bool notify);
    void undo (state::State& s, bool notify);
  };

};

#endif
