// Generated by dia2code
#ifndef ENGINE__BUILDCOMMAND__H
#define ENGINE__BUILDCOMMAND__H

#include <string>

namespace engine {
  class Command;
  class Engine;
}

#include "Command.h"
#include "Engine.h"

namespace engine {

  /// class BuildCommand - 
  class BuildCommand : public engine::Command {
    // Attributes
  public:
    Command cmd;
  protected:
    std::string building;
    // Operations
  public:
    int getBuildCommand () const;
    ~BuildCommand ();
    void execute () const;
  };

};

#endif
