// Generated by dia2code
#ifndef ENGINE__CAPTUREBUILDING__H
#define ENGINE__CAPTUREBUILDING__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class CaptureBuilding - 
  class CaptureBuilding : public engine::Action {
    // Attributes
  protected:
    int x;
    int y;
    state::StructureTypeID BuildingType;
    // Operations
  public:
    CaptureBuilding (int x, int y, state::StructureTypeID BuildingType);
  };

};

#endif
