// Generated by dia2code
#ifndef ENGINE__CAPTURECOMMAND__H
#define ENGINE__CAPTURECOMMAND__H

#include <iostream>

namespace state {
  class Infantry;
  class Structure;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"
#include "state/Infantry.h"
#include "state/Structure.h"

namespace engine {

  /// class CaptureCommand - 
  class CaptureCommand : public engine::Command {
    // Attributes
  protected:
    state::Infantry* capturer;
    state::Structure* captured;
    // Operations
  public:
    CaptureCommand (state::Infantry* capturer, state::Structure* captured);
    ~CaptureCommand ();
    CommandTypeID getCommandTypeID () const;
    state::Infantry* getCapturer ();
    state::Structure* getCaptured ();
  };

};

#endif
