// Generated by dia2code
#ifndef ENGINE__CAPTUREBUILDING__H
#define ENGINE__CAPTUREBUILDING__H

#include <iostream>

namespace state {
  class Structure;
};
namespace engine {
  class Action;
}

#include "state/Structure.h"
#include "Action.h"

namespace engine {

  /// class CaptureBuilding - 
  class CaptureBuilding : public engine::Action {
    // Attributes
  protected:
    int x;
    int y;
    state::Structure BuildingType;
    // Operations
  public:
    CaptureBuilding (int x, int y, state::Structure BuildingType);
  };

};

#endif
