// Generated by dia2code
#ifndef ENGINE__CAPTURE__H
#define ENGINE__CAPTURE__H

#include <iostream>

namespace state {
  class Infantry;
  class Structure;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "state/Structure.h"
#include "state/Infantry.h"

namespace engine {

  /// class Capture - 
  class Capture : public engine::Action {
    // Attributes
  protected:
    state::Infantry* capturer;
    state::Structure* captured;
    // Operations
  public:
    Capture (state::Infantry* capturer, state::Structure* captured);
    ~Capture ();
    void execute () const;
  };

};

#endif
