// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H

#include <iostream>

namespace engine {

  enum CommandTypeID {
    LOAD     = 0,
    ATTACKCOMMAND     = 1,
    PRODUCEFIGHTERCOMMAND     = 2,
    PRODUCEINFANTRYCOMMAND     = 3,
    CAPTURECOMMAND     = 4,
    MOVECOMMAND     = 5
  };

};

#endif
