// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


#include "CommandTypeID.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    engine::CommandTypeID commandTypeID;
    // Operations
  public:
    virtual ~Command ();
    virtual int getCategory () const;
    virtual CommandTypeID getTypeID () const;
  };

};

#endif
