// Generated by dia2code
#ifndef ENGINE__COMMANDSET__H
#define ENGINE__COMMANDSET__H

#include <iostream>
#include <vector>

namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class CommandSet - 
  class CommandSet {
    // Associations
    // Attributes
  public:
    std::vector<Command*> commands;
    // Operations
  public:
    CommandSet (std::vector<Command*> commands);
    ~CommandSet ();
    int size () const;
    Command* getCommand (int i);
    void setCommand (Command* command);
  };

};

#endif
