// Generated by dia2code
#ifndef ENGINE__ENGINEMODE__H
#define ENGINE__ENGINEMODE__H

#include <iostream>

namespace engine {

  enum EngineMode {
    PLAY     = 0,
    CLOSE     = 1
  };

};

#endif
