// Generated by dia2code
#ifndef ENGINE__MOVE__H
#define ENGINE__MOVE__H

#include <iostream>

namespace state {
  class Element;
  class ElementList;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "state/ElementList.h"
#include "state/Element.h"

namespace engine {

  /// class Move - 
  class Move : public engine::Action {
    // Attributes
  protected:
    state::Element* mover;
    state::Element* destination;
    state::ElementList* StaticMapElements;
    state::ElementList* MapUnits;
    // Operations
  public:
    Move (state::Element* mover, state::Element* destination, state::ElementList* StaticMapElements, state::ElementList* MapUnits);
    ~Move ();
    void execute () const;
  };

};

#endif
