// Generated by dia2code
#ifndef ENGINE__MOVEUNIT__H
#define ENGINE__MOVEUNIT__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MoveUnit - 
  class MoveUnit : public engine::Action {
    // Attributes
  protected:
    int index;
    int destination_x;
    int destination_y;
    // Operations
  public:
    MoveUnit (int index);
    void setCoords (int destination_x, int destination_y) const;
  };

};

#endif
