// Generated by dia2code
#ifndef ENGINE__MOVECOMMAND__H
#define ENGINE__MOVECOMMAND__H

#include <iostream>

namespace state {
  class Element;
  class ElementList;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"
#include "state/Element.h"
#include "state/ElementList.h"

namespace engine {

  /// class MoveCommand - 
  class MoveCommand : public engine::Command {
    // Attributes
  protected:
    state::Element* mover;
    state::Element* destination;
    state::ElementList* StaticMapElements;
    state::ElementList* MapUnits;
    // Operations
  public:
    MoveCommand (state::Element* mover, state::Element* destination, state::ElementList* StaticMapElements, state::ElementList* MapUnits);
    ~MoveCommand ();
    CommandTypeID getCommandTypeID () const;
    state::Element* getMover ();
    state::Element* getDestination ();
    state::ElementList* getStaticMapElements ();
    state::ElementList* getMapUnits ();
  };

};

#endif
