// Generated by dia2code
#ifndef ENGINE__PRODUCEUNIT__H
#define ENGINE__PRODUCEUNIT__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ProduceUnit - 
  class ProduceUnit : public engine::Action {
    // Attributes
  protected:
    int x;
    int y;
    state::MobileElement ProduceUnitType;
    // Operations
  public:
    ProduceUnit (int x, int y, state::MobileElement ProduceUnitType);
  };

};

#endif
