// Generated by dia2code
#ifndef ENGINE__PRODUCEINFANTRY__H
#define ENGINE__PRODUCEINFANTRY__H

#include <iostream>

namespace state {
  class ElementList;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "state/ElementList.h"

namespace engine {

  /// class ProduceInfantry - 
  class ProduceInfantry : public engine::Action {
    // Attributes
  protected:
    int x;
    int y;
    state::ElementList* ListOfElements;
    state::ElementList* ListOfTurn;
    int playerColor;
    // Operations
  public:
    ProduceInfantry (int x, int y, state::ElementList* ListOfElements, state::ElementList* ListOfTurn, int playerColor);
    ~ProduceInfantry ();
    void execute () const;
  };

};

#endif
