// Generated by dia2code
#ifndef ENGINE__RULER__H
#define ENGINE__RULER__H


namespace state {
  class State;
};
namespace engine {
  class CommandSet;
  class ActionList;
};
namespace state {
  class MobileElement;
  class StaticElement;
  class Structure;
}

#include "state/State.h"
#include "state/Structure.h"
#include "state/StaticElement.h"
#include "state/MobileElement.h"
#include "ActionList.h"

namespace engine {

  /// class Ruler - 
  class Ruler {
    // Associations
    // Attributes
  protected:
    const state::State& currentState;
    const CommandSet& commands;
    ActionList& actions;
    bool canAct;
    // Operations
  public:
   
    Ruler (ActionList& actions, const state::State& cstate , const CommandSet& command);
    ~Ruler ();
    void apply ();
    void setcanAct (bool can);
    bool getcanAct ();
    void moveChar (state::MobileElement* mover, state::StaticElement* destination);
    void attack (state::MobileElement* attacker, state::MobileElement* defender);
    void produce (state::State current, state::Structure building, state::MobileElement* unitproduce);
    void capture (state::MobileElement* capturer, state::Structure captured);
   /* state::Structure tileIsBuilding(<std::string> tileLetter);
    state::MobileElement tileIsMobileElement(<std::string> tileLetter);*/
  };

};

#endif
