// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H


namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class Animation - 
  class Animation {
    // Associations
    // Attributes
  public:
     tile_number;
  protected:
    int x;
    int y;
    const Tile* tile;
    state::Direction d;
    long int start;
    float speed;
    // Operations
  public:
    Animation (const Tile* tile);
    void setDirection (state::Direction d);
  };

};

#endif
