// Generated by dia2code
#ifndef RENDER__ANIMATEDTILE__H
#define RENDER__ANIMATEDTILE__H

#include <vector>

namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class AnimatedTile - 
  class AnimatedTile : public render::Tile {
    // Associations
    // Attributes
  public:
    std::vector<const Tile*> tiles;
    float rate;
    // Operations
  public:
    AnimatedTile (float r = 1);
    int ~AnimatedTile () const;
    bool isAnimated () const;
    void setRate (float r) const;
    float getRate () const;
    void addTile (Tile* tile);
    void setTile ( tile_number);
    const Tile* getTile (int tile_number) const;
  };

};

#endif
