// Generated by dia2code
#ifndef RENDER__ELEMENTLISTLAYER__H
#define RENDER__ELEMENTLISTLAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class ElementListLayer - Une des couches de la scène
Avec : les éléments (Mobiles et Statiques => grid et unités)
  class ElementListLayer : public render::Layer {
    // Operations
  public:
    void stateChanged (const State::StateEvent& e);
  protected:
    void update ( elementList::, int i);
  };

};

#endif
