// Generated by dia2code
#ifndef RENDER__ELEMENTLISTLAYER__H
#define RENDER__ELEMENTLISTLAYER__H


namespace render {
  class Layer;
};
namespace state {
  class State;
}

#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class ElementListLayer - 
  class ElementListLayer : public render::Layer {
    // Operations
  public:
    void stateChanged (const state::StateEvent& e);
  protected:
    void update (const state::ElementList& elementList, int i);
  };

};

#endif
