// Generated by dia2code
#ifndef RENDER__ELEMENTSTATE__H
#define RENDER__ELEMENTSTATE__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class ElementState - Une des couches de la scène
Avec : les éléments (Mobiles et Statiques => grid et unités)
  class ElementState : public render::Layer {
    // Operations
  public:
    void stateChanged (const State::StateEvent& e);
  protected:
    void update ( elementList::, int i);
  };

};

#endif
