// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H


namespace render {
  class Surface;
  class TileSet;
};
namespace state {
  class StateObserver;
}

#include "state/StateObserver.h"
#include "TileSet.h"
#include "Surface.h"

namespace render {

  /// class Layer - 
  class Layer : public state::StateObserver {
    // Associations
    // Attributes
  private:
    Surface* surface;
  protected:
    const TileSet* tileset;
    // Operations
  public:
    Layer ();
    virtual ~Layer ();
    const TileSet* getTileSet () const;
    void setTileSet (const TileSet* tileset);
    void setSurface (Surface* surface);
  };

};

#endif
