// Generated by dia2code
#ifndef RENDER__SCENELAYER__H
#define RENDER__SCENELAYER__H


namespace render {

  enum SceneLayer {
    GRID_LAYER     = 1,
    UNITS_LAYER     = 2,
    INFO_LAYER     = 3
  };

};

#endif
