// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <vector>

namespace render {
  class Layer;
  class Surface;
};
namespace state {
  class StateObserver;
};
namespace render {
  class ElementListLayer;
  class ElementState;
}

#include "state/StateObserver.h"
#include "ElementListLayer.h"
#include "ElementState.h"
#include "SceneLayer.h"

namespace render {

  /// class Scene - 
  class Scene : public state::StateObserver {
    // Associations
    // Attributes
  protected:
    std::vector<Layer*> layers;
    int width;
    int height;
    // Operations
  public:
    Scene ();
    ~Scene ();
    int getWidth () const;
    int getHeight () const;
    void setLayer (int index, Layer* layer);
    int getLayer () const;
    void setSurface (int index, Surface* surface);
    void registerObservers (const state ::State* s);
    void unregisterObservers (const state::State* s);
    void StateChanged (const state::StateEvent& e);
  };

};

#endif
