// Generated by dia2code
#ifndef RENDER__STATICTILE__H
#define RENDER__STATICTILE__H


namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class StaticTile - 
  class StaticTile : public render::Tile {
    // Attributes
  protected:
    int x;
    int y;
    int width;
    int height;
    // Operations
  public:
    StaticTile (int x = 0, int y = 0, int w = 16, int h = 16);
    bool isAnimated () const;
    int getX ( ) const;
    int getY () const;
    int getWidth () const;
    int getHeight () const;
    int setX (int x) const;
    int setY (int y) const;
    int setWidth (int w) const;
    int setHeight (int h) const;
  };

};

#endif
