// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H


namespace render {
  class StaticTile;
}

namespace render {

  /// class Surface - 
  class Surface {
    // Operations
  public:
    virtual ~Surface ();
    void clear ();
    void loadTexture (const char* image_file);
    void setSpriteLocation (int i, int x, int y);
    virtual void setSpriteTexture (int i, const StaticTile* tex);
  };

};

#endif
