// Generated by dia2code
#ifndef IA__AI__H
#define IA__AI__H

#include <iostream>

namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace state {
  class Infantry;
  class Fighter;
  class MobileElement;
  class Structure;
  class StaticElement;
}

#include "engine/Engine.h"
#include "state/State.h"
#include "state/Infantry.h"
#include "state/Fighter.h"
#include "state/MobileElement.h"
#include "state/Structure.h"
#include "state/StaticElement.h"

namespace ia {

  /// class AI - 
  class AI {
    // Attributes
  protected:
    state::State* mainState;
    engine::Engine* mainEngine;
    // Operations
  public:
    AI ();
    AI (state::State* mainState, engine::Engine* mainEngine);
    ~AI ();
    bool nextLocation (int xdep, int ydep, int xarr, int yarr) const;
  };

};

#endif
