// Generated by dia2code
#ifndef IA__HEURISTICAI__H
#define IA__HEURISTICAI__H

#include <iostream>

namespace ia {
  class PathMap;
  class DumbIA;
}

#include "PathMap.h"
#include "DumbIA.h"

namespace ia {

  /// class HeuristicAI - 
  class HeuristicAI : public ia::DumbIA {
    // Associations
    // Attributes
  protected:
    PathMap HQ;
    PathMap Unit;
    PathMap Neutral;
    // Operations
  public:
    void moveToNeutral (const PathMap& map, int idx);
    const PathMap&  getUnit () const;
    const PathMap& getHQ () const;
    const PathMap& getNeutral () const;
  protected:
    void moveToHQ (int idx, const PathMap& map);
    void moveToUnit (int idx, const PathMap& map);
  };

};

#endif
