// Generated by dia2code
#ifndef IA__PATHMAP__H
#define IA__PATHMAP__H

#include <iostream>

namespace ia {

  /// class PathMap - 
  class PathMap {
    // Attributes
  protected:
    int width;
    int height;
     weights;
    // Operations
  public:
    PathMap ();
    ~PathMap ();
    int getWidth () const;
    int getHeight () const;
    int getWeight () const;
    void setWeight (int x, int y, int w) const;
  };

};

#endif
