// Generated by dia2code
#ifndef STATE__AIR__H
#define STATE__AIR__H


namespace state {
  class MobileElement;
}

#include "MobileElement.h"

namespace state {

  /// class Air - 
  class Air : public state::MobileElement {
    // Operations
  public:
    virtual bool const isAir () = 0;
  };

};

#endif
