// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  enum Direction {
    NONE     = 0,
    NORTH     = 1,
    EAST     = 2,
    SOUTH     = 3,
    WEST     = 4
  };

};

#endif
