// Generated by dia2code
#ifndef STATE__ELEMENTLIST__H
#define STATE__ELEMENTLIST__H

#include <vector>

namespace state {
  class Element;
  class State;
  class ElementList;
}

namespace state {

  /// class ElementList - 
  class ElementList {
    // Attributes
  public:
    std::vector<Element*> elements;
  protected:
    State& s;
    // Operations
  public:
    ElementList (State& s);
    ~ElementList ();
    bool const equals (const ElementList& other);
    const State& getState () const;
    int const size ();
    Element* const get (int i);
    void clear ();
    void set (int i, Element* e);
  };

};

#endif
