// Generated by dia2code
#ifndef STATE__ELEMENTLIST__H
#define STATE__ELEMENTLIST__H

#include <vector>

namespace state {
  class Element;
  class State;
  class ElementList;
  class Observable;
}

#include "Observable.h"

namespace state {

  /// class ElementList - 
  class ElementList : public state::Observable {
    // Attributes
  public:
    std::vector<Element*> elements;
  protected:
    State& s;
    // Operations
  public:
    ElementList (State& s);
    ~ElementList ();
    bool equals (const ElementList& other) const;
    const State& getState () const;
    int const size ();
    Element* get (int i) const;
    void clear ();
    void set (int i, Element* e);
  };

};

#endif
