// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

#include "Direction.h"
#include "TypeID.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  protected:
    /// Coordonnée en abscisse
    int x;
    /// Coordonnée en ordonnée
    int y;
    Direction orientation;
    // Operations
  public:
    Element ();
    virtual ~Element ();
    int getX() const;
    int getY() const;
    Direction const getOrientation ();
    void setX (int x);
    void setY (int y);
    void setOrientation (Direction o);
    virtual bool const isStatic ();
    virtual TypeID const getTypeID ();
    virtual bool const equals (const Element& other) = 0;
  };

};

#endif
