// Generated by dia2code
#ifndef STATE__FIGHTER__H
#define STATE__FIGHTER__H


namespace state {
  class Element;
  class Air;
}

#include "Air.h"

namespace state {

  /// class Fighter - 
  class Fighter : public state::Air {
    // Operations
  public:
    Fighter ();
    TypeID const getTypeID ();
    bool const equals (const Element& other) override;
  };

};

#endif
