// Generated by dia2code
#ifndef STATE__FIGHTER__H
#define STATE__FIGHTER__H

#include <iostream>

namespace state {
  class Element;
  class Air;
}

#include "TypeID.h"
#include "Air.h"

namespace state {

  /// class Fighter - 
  class Fighter : public state::Air {
    // Operations
  public:
    Fighter ();
    TypeID  getTypeID () const;
    bool equals (const Element& other) const;
    bool isAir () const;
  };

};

#endif
