// Generated by dia2code
#ifndef STATE__GROUND__H
#define STATE__GROUND__H


namespace state {
  class MobileElement;
}

#include "MobileElement.h"

namespace state {

  /// class Ground - 
  class Ground : public state::MobileElement {
    // Operations
  public:
    virtual bool isAir () const = 0;
  };

};

#endif
