// Generated by dia2code
#ifndef STATE__INFANTRY__H
#define STATE__INFANTRY__H


namespace state {
  class Element;
  class Ground;
}

#include "Ground.h"

namespace state {

  /// class Infantry - 
  class Infantry : public state::Ground {
    // Operations
  public:
    Infantry ();
    TypeID const getTypeID ();
    bool const equals (const Element& other);
  };

};

#endif
