// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H


namespace state {
  class Element;
}

#include "Direction.h"
#include "TypeID.h"
#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Associations
    state::Direction direction;
    // Attributes
  protected:
    int speed;
    int position;
    int color;
    bool rank;
    int hitpoints;
    int damage;
    int cost;
    TypeID type;
    // Operations
  public:
    MobileElement ();
    int getSpeed () const;
    int getPosition () const;
    void setSpeed (int sp);
    void setPosition (int pos);
    /// Mobile ou Statique ?
    bool isStatic () const;
    virtual bool isAir () const;
    virtual bool equals (const Element& other) const = 0;
    void setColor (int c);
    int const getColor ();
    void setRank (bool rank);
    bool getRank () const;
    void setHp (int hp);
    int getHp () const;
    void setDamage (int d);
    int getDamage () const;
    void setCost (int co);
    int getCost () const;
    virtual TypeID getTypeID () const=0;
    void setTypeID(state::TypeID a);
  };

};

#endif
