// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <iostream>

namespace state {

  /// class Player - 
  class Player {
    // Attributes
  protected:
    int iron;
    int units;
    int color;
    // Operations
  public:
    Player ();
    void setIron (int iron);
    void setUnits (int nbunits);
    void setColor (int playercolor);
    int getIron ();
    int getUnits ();
    int getColor ();
  };

};

#endif
