// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H


namespace state {

  enum SpaceTypeID {
    ROAD     = 1,
    GRASS     = 2,
    MINE     = 3,
    BUILDING     = 4,
    HEADQUARTER     = 5,
    FACTORY     = 6,
    AIRPORT     = 7
  };

};

#endif
