// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class Element;
  class StaticElement;
}
#include <typeinfo>
#include "SpaceTypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement{
    // Associations
    // Operations
  public:
    Space (SpaceTypeID sid);
    bool const isSpace ();
    TypeID const getTypeID ();
    SpaceTypeID const getSpaceTypeID ();
    void setSpaceTypeID (SpaceTypeID sid);
    bool const equals (const Element& other);
  };

};

#endif
