// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class Element;
  class StaticElement;
}

#include "SpaceTypeID.h"
#include "TypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Associations
    state::SpaceTypeID spaceTypeID;
    // Attributes
  protected:
    bool free;
    // Operations
  public:
    Space (SpaceTypeID sid);
    bool isSpace () const;
    TypeID getTypeID () const;
    SpaceTypeID getSpaceTypeID () const;
    void setSpaceTypeID (SpaceTypeID sid, bool free);
    bool equals (const Element& other) const;
    bool isFree ();
  };

};

#endif
