// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H

#include <iostream>

namespace state {

  enum SpaceTypeID {
    verticalROAD     = 1,
    horizontalROAD     = 2,
    bottomRightROAD     = 3,
    bottomLeftROAD     = 4,
    topLeftROAD     = 5,
    TopRightROAD     = 6,
    ROAD     = 7,
    GRASS     = 8
  };

};

#endif
