// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementList;
  class ElementGrid;
  class MobileElement;
}

#include "ElementList.h"
#include "ElementGrid.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  protected:
    ElementList chars;
    ElementGrid grid;
    int iron;
    int units;
    // Operations
  public:
    State ();
    ~State ();
    int getIron() const;
    int getUnit() const;
    
   
    ElementGrid& getGrid ();
    
    ElementList& getChars ();
    
    MobileElement* getChar (int idx);
    
    void setIron (int res);
    void setUnits (int count);
    void setGrid (const ElementGrid& grid);
    void setChars (const ElementList& list);
  };

};

#endif
