// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H

#include <iostream>

namespace state {

  enum StateEventID {
    UNIT_MOVE     = 1,
    UNIT_KILLED     = 2,
    UNIT_PROMOTE     = 3,
    BUILDING_CAPTURED     = 4,
    UNIT_COUNT     = 5,
    IRON_COUNT     = 6,
    SPEED_CHANGED     = 7,
    ALL_CHANGED     = 8
  };

};

#endif
