// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H

#include <iostream>

namespace state {
  class Element;
}

#include "TypeID.h"
#include "Element.h"

namespace state {

  /// class StaticElement - 
  class StaticElement : public state::Element {
    // Operations
  public:
    bool isStatic () const;
    virtual bool isSpace () const;
    virtual bool isFree () const;
    virtual TypeID getTypeID () const;
  };

};

#endif
