// Generated by dia2code
#ifndef STATE__STRUCTURE__H
#define STATE__STRUCTURE__H


namespace state {
  class Element;
  class StaticElement;
}

#include "StructureTypeID.h"
#include "TypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Structure - 
  class Structure : public state::StaticElement {
    // Associations
    state::StructureTypeID structureTypeID;
    // Attributes
  protected:
    int color;
    int capturepoints;
    bool free;
    // Operations
  public:
    Structure ();
    Structure (StructureTypeID sid, bool free, int color);
    bool isFree () const;
    TypeID getTypeID () const;
    StructureTypeID getStructureTypeID () const;
    void setStructureTypeID (StructureTypeID sid, bool free);
    bool equals (const Element& other) const;
    int getColor () const;
    void setColor (int c);
    int getCapturepoints () const;
    void setCapturepoints (int cp);
  };

};

#endif
