// Generated by dia2code
#ifndef STATE__STRUCTURETYPEID__H
#define STATE__STRUCTURETYPEID__H


namespace state {

  enum StructureTypeID {
    MINE     = 1,
    BUILDING     = 2,
    HEADQUARTER     = 3,
    FACTORY     = 4,
    AIRPORT     = 5
  };

};

#endif
