// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H

#include <iostream>

namespace state {
  class Element;
  class Ground;
}

#include "TypeID.h"
#include "Ground.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Ground {
    // Operations
  public:
    Tank ();
    TypeID getTypeID () const;
    bool  equals (const Element& other) const;
    bool isAir () const;
  };

};

#endif
