// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H


namespace state {
  class Element;
  class Ground;
}
#include <typeinfo>
#include "Ground.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Ground {
    // Operations
  public:
    Tank ();
    TypeID const getTypeID ();
    bool const equals (const Element& other);
  };

};

#endif
