// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeID {
    WALL     = 0,
    SPACE     = 1,
    FIGHTER     = 2,
    INFANTRY     = 3,
    TANK     = 4,
    ANTIAIR     = 5
  };

};

#endif
