// Generated by dia2code
#ifndef STATE__WALL__H
#define STATE__WALL__H


namespace state {
  class Element;
  class StaticElement;
}

#include "WallTypeID.h"
#include "TypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Wall - 
  class Wall : public state::StaticElement {
    // Associations
    state::WallTypeID wallTypeID;
    // Attributes
  protected:
    bool free;
    // Operations
  public:
    Wall (WallTypeID wid);
    bool isSpace () const;
    WallTypeID getWallTypeID () const;
    void setWallTypeID (WallTypeID wid);
    bool equals (const Element& other) const;
    TypeID getTypeID () const;
    bool isFree () const;
  };

};

#endif
