// Generated by dia2code
#ifndef STATE__WALL__H
#define STATE__WALL__H


namespace state {
  class Element;
  class StaticElement;
}
#include <typeinfo>
#include "WallTypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Wall - 
  class Wall : public state::StaticElement {
    // Associations
    state::WallTypeID wallTypeID;
    // Operations
  public:
    Wall (WallTypeID wid);
    bool const isSpace ();
    TypeID const getTypeID ();
    WallTypeID const getWallTypeID ();
    void setWallTypeID (WallTypeID wid);
    bool const equals (const Element& other);
  };

};

#endif
