// Generated by dia2code
#ifndef STATE__WALLTYPEID__H
#define STATE__WALLTYPEID__H


namespace state {

  enum WallTypeID {
    SEA     = 1,
    horizontalWater     = 2,
    topWater     = 3,
    leftWater     = 4,
    verticalWater     = 5,
    bottomWater     = 6,
    rightWater     = 7,
    WOODS     = 8
  };

};

#endif
