// Generated by dia2code
#ifndef __SERVER__H
#define __SERVER__H

#include "server/ServerEvent.h"
#include "server/ServerObserver.h"
#include "server/Observable.h"
#include "server/Server.h"
#include "server/LocalServer.h"
#endif
