// Generated by dia2code
#ifndef CLIENT__SFMLCLIENT__H
#define CLIENT__SFMLCLIENT__H

#include <iostream>
#include <SFML/Graphics.hpp>

namespace client {
  class Client;
}

#include "Client.h"

namespace client {

  /// class SFMLClient - 
  class SFMLClient : public client::Client {
    // Attributes
  protected:
    sf::RenderWindow window;
    // Operations
  public:
    SFMLClient ();
  protected:
    void init ();
    bool acquireControls ();
    void stateChanged ();
  };

};

#endif
